Repository cupicks/cupicks-be, pull requests merged in 2022-08, with the labels that each got.

#1 PR : /api/auth/singup controller 구현
  branch.sample.ts
  src/app.ts
  src/models/_.loader.ts
  src/models/dtos/i.base.dto.ts
  src/models/dtos/signup.user.dto.ts
  src/models/exceptions/custom.exception.ts
  src/modules/_.lodaer.ts
  src/modules/validators/joi.validator.ts
  src/routes/controllers/_.exporter.ts
  src/routes/controllers/auth.controller.ts
  src/routes/routers/auth.router.ts
  src/server.ts
Labels: feature

#8 PR : Install `bcrypt` `jsonwebtoken` with @types
  package-lock.json
  package.json
Labels: lib

#12 PR : bcrypt 공급자 생성 / bcrypt.provider.ts
  package-lock.json
  package.json
  src/app.ts
  src/constants/_.loader.ts
  src/models/_.loader.ts
  src/models/env/env.ts
  src/models/exceptions/custom.exception.ts
  src/modules/_.loader.ts
  src/modules/_.lodaer.ts
  src/modules/providers/bcrypt.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/server.ts
Labels: feature

#10 PR : Jwt 공급자 함수와 협력자 구현
  branch.sample.ts
  jest.config.json
  package-lock.json
  package.json
  src/constants/_.loader.ts
  src/constants/types/t.algorithm.ts
  src/models/_.loader.ts
  src/models/env/env.ts
  src/models/env/private/env.private.ts
  src/models/exceptions/custom.exception.ts
  src/modules/_.lodaer.ts
  src/modules/providers/env.provider.ts
  src/modules/providers/jwt.provider.ts
  src/server.ts
Labels: feature

#14 PR : MysqlProvider db 공급자 함수 구현
  src/models/_.loader.ts
  src/models/env/env.ts
  src/models/exceptions/custom.exception.ts
  src/modules/_.loader.ts
  src/modules/_.lodaer.ts
  src/modules/providers/bcrypt.provider.ts
  src/modules/providers/env.provider.ts
  src/modules/providers/mysql.provider.ts
  src/modules/validators/joi.validator.ts
  src/routes/controllers/recipe.controller.ts
  src/server.ts
Labels: feature, lib

#16 PR : 회원가입 기능 구현
  src/models/_.loader.ts
  src/models/dtos/user/signup.user.dto.ts
  src/models/dtos/user/singin.user.dto.ts
  src/models/dtos/user/user.dto.ts
  src/modules/providers/bcrypt.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/_.exporter.ts
  src/routes/repositories/auth.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/services/_.exporter.ts
  src/routes/services/auth.service.ts
Labels: feature
