Repository cupicks/cupicks-be, pull requests merged in 2022-09, with the labels that each got.

#22 PR : 로그인 기능 구현, issue#18 #20
  .gitignore
  package-lock.json
  sql/default.sql
  sql/dev.sql
  sql/prod.sql
  sql/test.sql
  src/app.ts
  src/middlewares/filters/_.exporter.ts
  src/middlewares/filters/content-type/application.json.filter.ts
  src/middlewares/filters/content-type/application.x.www.form.urlencoded.filter.ts
  src/models/_.loader.ts
  src/models/env/env.ts
  src/models/env/private/env.private.ts
  src/models/packets/i.user.packet.ts
  src/modules/providers/bcrypt.provider.ts
  src/modules/providers/jwt.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/services/auth.service.ts
Labels: bug, feature

#24 PR : 테스트 코드 폴더 구조 완성 및 가이드 문서, issue #23
  package.json
  test/README.md
Labels: documentation

#27 PR : 회원가입 및 로그인, 테이블 칼럼 길이 등 잔버그 수정 #25, #26
  sql/default.sql
  sql/dev.sql
  sql/prod.sql
  sql/test.sql
  src/routes/repositories/auth.repository.ts
  src/routes/services/auth.service.ts
Labels: feature, refactor

#29 PR : JwtProvider 지네릭 메서드로 추상화 진행, #28
  package.json
  src/modules/providers/jwt.provider.ts
Labels: bug, refactor

#9 PR : 레시피 작성 기능 구현
  package-lock.json
  package.json
  src/models/_.loader.ts
  src/models/dtos/recipe/create.recipe.dto.ts
  src/models/env/env.ts
  src/models/exceptions/custom.exception.ts
  src/modules/_.loader.ts
  src/modules/providers/multer.provider.ts
  src/routes/controllers/_.exporter.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/_.exporter.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/_.exporter.ts
  src/routes/services/recipe.service.ts
  src/server.ts
Labels: feature

#31 PR : 토큰 재발행 구현
  src/models/_.loader.ts
  src/models/dtos/user/publish.token.dto.ts
  src/models/exceptions/custom.exception.ts
  src/models/packets/i.user.packet.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/services/auth.service.ts
Labels: feature

#36 PR : content-type multipart/form-data 필터 구현
  src/app.ts
  src/middlewares/filters/_.exporter.ts
  src/middlewares/filters/content-type/form.data.filter.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/routers/recipe.router.ts
Labels: feature

#38 PR : MulterProvider 메서드 수정 `multer.provider.ts`
  src/modules/providers/multer.provider.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/recipe.service.ts
Labels: bug

#39 PR : 회원가입 로직에 업로드 기능 추가
  src/middlewares/filters/content-type/form.data.filter.ts
  src/modules/providers/multer.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/routers/auth.router.ts
Labels: feature

#41 PR : 유저 인증 미들웨어 추가 버전 완료 `src/routes/recipe`
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/recipe.service.ts
Labels: feature

#47 PR : 본인확인 도메인 구현 완료, #46
  src/models/_.loader.ts
  src/models/dtos/user/confirm.password.dto.ts
  src/models/dtos/user/publish.token.dto.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/services/auth.service.ts
Labels: feature

#52 PR : 1주차 기술 피드백 - 코드리뷰 항목
  src/app.ts
  src/modules/providers/jwt.provider.ts
  src/modules/providers/multer.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/routers/_.exporter.ts
  src/routes/routers/auth.router.ts
  src/routes/routers/profile.router.ts
Labels: feedback

#56 PR : AccessToken Payload 에 nickname 추가, #55
  src/modules/providers/jwt.provider.ts
  src/routes/services/auth.service.ts
Labels: feature

#57 PR : EnvProvider 에 분기점 추가, #40
  .gitignore
  src/modules/providers/env.provider.ts
  src/server.ts
Labels: refactor

#58 PR : 댓글 작성 기능 구현 `src/`
  package-lock.json
  sql/dev.sql
  src/app.ts
  src/models/_.loader.ts
  src/models/dtos/comment/comment.dto.ts
  src/models/dtos/user/signup.user.dto.ts
  src/modules/providers/multer.provider.ts
  src/routes/controllers/_.exporter.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/_.exporter.ts
  src/routes/repositories/comment.auth.repository.ts
  src/routes/routers/_.exporter.ts
  src/routes/routers/comment.router.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/_.exporter.ts
  src/routes/services/comment.service.ts
Labels: feature

#59 PR : API 명세 수정사항 반영 `src`
  src/middlewares/multer.middleware.ts
  src/modules/providers/multer.provider.ts
  src/routes/controllers/comment.controller.ts
  src/routes/routers/comment.router.ts
Labels: feature

#60 PR : API 명세 수정사항 반영 `src`
  src/middlewares/multer.middleware.ts
  src/routes/controllers/comment.controller.ts
Labels: feature

#65 PR : JwtProvider 확장 인터페이스 수정, #63
  src/modules/providers/jwt.provider.ts
  src/routes/services/auth.service.ts
Labels: refactor, feedback

#67 PR : Simplify SQL user table, #66
  sql/default.sql
  sql/dev.sql
  sql/prod.sql
  sql/test.sql
  src/routes/repositories/auth.repository.ts
  src/routes/services/auth.service.ts
Labels: refactor, feedback

#69 PR : 주석 제거 `comment.controller.ts`
  src/modules/providers/multer.provider.ts
  src/routes/controllers/comment.controller.ts
  src/routes/repositories/comment.auth.repository.ts
  src/routes/routers/comment.router.ts
  src/routes/services/comment.service.ts
Labels: feature

#70 PR : Update 코멘트 삭제 시 s3 이미지 삭제 구현 `src/routers`
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/comment.auth.repository.ts
  src/routes/routers/comment.router.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/comment.service.ts
Labels: feature

#71 PR : 코멘트 업데이트 시 기존 s3 이미지 삭제 후 생성 구현 `src/routes`
  src/routes/controllers/comment.controller.ts
  src/routes/repositories/comment.auth.repository.ts
  src/routes/routers/comment.router.ts
  src/routes/services/comment.service.ts
Labels: feature

#72 PR : Create 레시피에 대한 코멘트 조회 기능 구현 `src/`
  src/constants/_.loader.ts
  src/constants/types/t.comment.response.ts
  src/models/dtos/comment/comment.dto.ts
  src/routes/controllers/comment.controller.ts
  src/routes/repositories/comment.auth.repository.ts
  src/routes/routers/comment.router.ts
  src/routes/services/comment.service.ts
Labels: feature

#73 PR : 레시피 삭제 기능 구현 `src/`
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/comment.auth.repository.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/comment.service.ts
  src/routes/services/recipe.service.ts
Labels: feature

#77 PR : AwsSesProvider 이메일 발송 공급자 구현
  package-lock.json
  package.json
  sql/default.sql
  sql/dev.sql
  sql/prod.sql
  sql/test.sql
  src/models/_.loader.ts
  src/models/env/env.ts
  src/modules/_.loader.ts
  src/modules/providers/aws.ses.provider.ts
  src/routes/repositories/.gitkeep
  src/routes/services/.gitkeep
  src/server.ts
Labels: feature, feedback

#81 PR : 람다 이미지 리사이징 구현 `lambda/`
  lambda/index.js
  lambda/package-lock.json
  lambda/package.json
Labels: feature

#83 PR : 이메일 인증번호 확인 구현, #68
  sql/default.sql
  sql/dev.sql
  sql/prod.sql
  sql/test.sql
  src/models/dtos/user/confirm.email.dto.ts
  src/models/dtos/user/send.email.dto.ts
  src/models/dtos/user/signup.user.dto.ts
  src/models/dtos/user/singin.user.dto.ts
  src/models/packets/i.email.verify.packet.ts
  src/modules/_.loader.ts
  src/modules/providers/aws.ses.provider.ts
  src/modules/providers/date.provider.ts
  src/modules/providers/jwt.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/auth.verify.list.repository.ts
  src/routes/services/auth.service.ts
Labels: feature, feedback

#84 PR : 닉네임 중복확인 구현, #68
  src/models/dtos/user/confirm.nickname.dto.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/repositories/auth.verify.list.repository.ts
  src/routes/services/auth.service.ts
Labels: feature, feedback

#86 PR : 회원가입 로직 수정
  src/models/dtos/user/signup.user.dto.ts
  src/modules/providers/aws.ses.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/services/auth.service.ts
Labels: refactor, feedback

#89 PR : 레시피 싫어요 기능 구현 `src/`
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/recipe.service.ts
Labels: feature

#90 PR : Create 레시피 상세 조회 구현 `src/`
  src/constants/_.loader.ts
  src/constants/types/t.recipe.response.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/recipe.service.ts
Labels: feature

#96 cupicks@1.2.1
  .gitignore
  lambda/index.js
  lambda/package-lock.json
  lambda/package.json
  package.json
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/routers/comment.router.ts
  src/routes/routers/recipe.router.ts
Labels: bug, refactor

#110 PR : 임시 비밀번호 발급 구현
  src/models/_.loader.ts
  src/models/dtos/user/send.password.dto.ts
  src/modules/_.loader.ts
  src/modules/generator/random.generator.ts
  src/modules/providers/aws.ses.provider.ts
  src/modules/providers/jwt.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/routers/auth.router.ts
  src/routes/services/auth.service.ts
  src/server.ts
  tsconfig.json
Labels: feature

#111 PR : 임시 비밀번호 발송 도메인에 단방향 암호화 반영
  src/modules/providers/aws.ses.provider.ts
  src/routes/services/auth.service.ts
Labels: bug, refactor

#113 PR : 발급된 임시 비밀번호 서버에 반영
  src/app.ts
  src/middlewares/guards/cors/cors.guard.ts
  src/models/_.loader.ts
  src/models/dtos/user/reset.password.dto.ts
  src/models/env/env.ts
  src/modules/providers/aws.ses.provider.ts
  src/modules/providers/jwt.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/services/auth.service.ts
  src/server.ts
Labels: feature

#117 PR : 사용자 이메일 발송횟수 제한, #116 #118
  package-lock.json
  package.json
  sql/default.sql
  sql/dev.sql
  sql/prod.sql
  sql/test.sql
  src/models/packets/i.email.verify.packet.ts
  src/modules/_.loader.ts
  src/modules/providers/date.provider.ts
  src/modules/providers/dayjs.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/auth.verify.list.repository.ts
  src/routes/services/auth.service.ts
Labels: feature, refactor

#119 PR : 이메일 중복확인 메일 발송 제한 추가 수정, #116 #118
  src/models/env/env.ts
  src/models/packets/i.user.packet.ts
  src/modules/providers/aws.ses.provider.ts
  src/modules/providers/dayjs.provider.ts
  src/modules/providers/jwt.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/services/auth.service.ts
Labels: refactor

#122 PR : 레시피 전체 조회 구현
  src/constants/types/t.comment.response.ts
  src/models/_.loader.ts
  src/models/dtos/recipe/get.recipe.dto.ts
  src/models/dtos/recipe/ingredient.dto.ts
  src/models/dtos/recipe/recipe.dto.ts
  src/models/packets/i.recipe.ingredient.list.packet.ts
  src/models/packets/i.recipe.ingredient.packet.ts
  src/models/packets/i.recipe.packet.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/_.exporter.ts
  src/routes/repositories/comment.repository.ts
  src/routes/repositories/recipe.ingredient.list.repository.ts
  src/routes/repositories/recipe.ingredient.repository.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/comment.service.ts
  src/routes/services/recipe.service.ts
Labels: bug, feature

#123 cupicks@1.3.1
  src/constants/types/t.comment.response.ts
  src/models/_.loader.ts
  src/models/dtos/recipe/get.recipe.dto.ts
  src/models/dtos/recipe/ingredient.dto.ts
  src/models/dtos/recipe/recipe.dto.ts
  src/models/packets/i.recipe.ingredient.list.packet.ts
  src/models/packets/i.recipe.ingredient.packet.ts
  src/models/packets/i.recipe.packet.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/_.exporter.ts
  src/routes/repositories/comment.repository.ts
  src/routes/repositories/recipe.ingredient.list.repository.ts
  src/routes/repositories/recipe.ingredient.repository.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/comment.service.ts
  src/routes/services/recipe.service.ts
Labels: bug, feature

#125 Feature/get recipes
  src/constants/_.loader.ts
  src/constants/types/t.comment.response.ts
  src/models/_.loader.ts
  src/models/dtos/comment/get.comment.dto.ts
  src/models/packets/i.comment.packet.ts
  src/models/packets/i.recipe.packet.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/comment.repository.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/comment.service.ts
  src/routes/services/recipe.service.ts
Labels: bug, feature, refactor

#131 PR : CI/CD 성공
  .github/workflows/codedeploy.yml
  appspec.yml
  package-lock.json
  package.json
  sample.txt
  scripts/after-deploy.sh
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/comment.router.ts
  src/server.ts
  vite.config.ts
Labels: feature

#145 cupick@1.3.4.2
  src/models/env/env.ts
Labels: bug

#148 PR : 내가 업로드한 레시피 조회
  src/models/_.loader.ts
  src/models/dtos/profile/edit.profile.dto.ts
  src/models/dtos/profile/get.my.recipe.dto.ts
  src/models/packets/i.recipe.combined.packet.ts
  src/models/packets/i.recipe.packet.ts
  src/routes/controllers/profile.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/profile.router.ts
  src/routes/services/profile.service.ts
  src/routes/services/recipe.service.ts
Labels: feature

#150 PR : 내가 좋아요한 레시피 조회 기능
  src/models/dtos/profile/get.like.recipe.dto.ts
  src/routes/controllers/profile.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/profile.router.ts
  src/routes/services/profile.service.ts
Labels: feature

#151 cupick@1.3.4.3
  sql/default.sql
  sql/dev.sql
  sql/erd/ERD.mwb
  sql/prod.sql
  sql/test.sql
  src/models/_.loader.ts
  src/models/dtos/comment/create.comment.dto.ts
  src/models/dtos/comment/update.comment.dto.ts
  src/models/dtos/profile/edit.profile.dto.ts
  src/models/dtos/profile/get.like.recipe.dto.ts
  src/models/dtos/profile/get.my.recipe.dto.ts
  src/models/dtos/request.query.extractor.ts
  src/models/dtos/user/signup.user.dto.ts
  src/models/dtos/user/user.dto.ts
  src/models/packets/i.recipe.combined.packet.ts
  src/models/packets/i.recipe.packet.ts
  src/modules/providers/multer.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/profile.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/repositories/comment.repository.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/routers/profile.router.ts
  src/routes/services/auth.service.ts
  src/routes/services/comment.service.ts
  src/routes/services/profile.service.ts
  src/routes/services/recipe.service.ts
Labels: bug

#153 HotFix : 레시피 반환 도메인의 반환값에nickname, imageUrl,. resizedUrl 값 추가
  package-lock.json
  package.json
  src/models/dtos/recipe/recipe.dto.ts
  src/models/packets/i.recipe.combined.packet.ts
  src/models/packets/i.user.packet.ts
  src/routes/repositories/auth.repository.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/profile.service.ts
  src/routes/services/recipe.service.ts
Labels: bug, refactor

#155 HotFix 잘못 연결된 preventLoginUserGuard -> preventUnLoginUserGuard
  src/routes/routers/auth.router.ts
Labels: bug

#152 PR : auth 도메인에 전반적인 리펙터링 진행
  src/routes/repositories/auth.verify.list.repository.ts
  src/routes/services/auth.service.ts
Labels: bug

#103 PR : 테스트 - 환경변수 시스템(1/1), JoiValidator(1/3)
  package-lock.json
  package.json
  test/_.fake.datas/fixture/user.dto.fixture.ts
  test/integration/.gitkeep
  test/integration/env.system.test.ts
  test/integration/validate.system.test.ts
  test/unit/models/.gitkeep
Labels: test

#157 cupick@1.3.4.4
  .github/workflows/auto.deploy.yml
  .github/workflows/auto.jest.runner.yml
  package-lock.json
  package.json
  src/routes/repositories/auth.verify.list.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/services/auth.service.ts
  test/_.fake.datas/fixture/user.dto.fixture.ts
  test/integration/.gitkeep
  test/integration/env.system.test.ts
  test/integration/validate.system.test.ts
  test/unit/models/.gitkeep
Labels: bug, lib, test

#158 cupick@1.3.4.5
  scripts/after-deploy.sh
Labels: bug

#160 HotFix 회원가입에 잘못된 조건문 분기 처리 수정
  src/routes/services/auth.service.ts
Labels: bug

#161 HotFix 레시피 상세 조회에 누락된 nickname, imageUrl, resizedUrl 전달
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
Labels: bug, refactor

#162 TEST : 기본적인 `~routes/*/_.exporter` 테스트 코드 작성
  package.json
  src/models/exceptions/custom.exception.ts
  test/_.fake.datas/fixture/exception.fixture.ts
  test/integration/env.system.test.ts
  test/integration/sample.test.ts
  test/unit/models/env/env.test.ts
  test/unit/models/exception/custom.exception.test.ts
  test/unit/routes/controllers/_.exporter.test.ts
  test/unit/routes/repositories/_.exporter.test.ts
  test/unit/routes/routers/_.exporter.test.ts
  test/unit/routes/services/_.exporter.test.ts
Labels: test

#163 TEST : Test 샘플 테스트 코드 추가
  test/integration/sample.test.ts
  test/unit/models/env/env.test.ts
Labels: test

#174 PR :유지보수를 위한 TERROR_CODE 추가
  src/constants/_.loader.ts
  src/constants/error_list/error.list.ts
  src/middlewares/multer.middleware.ts
  src/models/exceptions/custom.exception.ts
  src/modules/providers/bcrypt.provider.ts
  src/modules/providers/jwt.provider.ts
  src/modules/providers/multer.provider.ts
  src/modules/providers/mysql.provider.ts
  src/modules/validators/joi.validator.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/profile.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/repositories/auth.verify.list.repository.ts
  src/routes/repositories/comment.repository.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/auth.service.ts
  src/routes/services/comment.service.ts
  src/routes/services/profile.service.ts
  src/routes/services/recipe.service.ts
  test/unit/models/exception/custom.exception.test.ts
Labels: refactor

#176 cupick@1.3.4.7
  src/constants/error_list/error.list.ts
  src/routes/services/comment.service.ts
  src/routes/services/recipe.service.ts
Labels: bug

#178 PR : UuidProvider 공급자 추가와 UuidProvider 를 활용한 s3 이미지 저장 로직 개선 `./src/*`
  package-lock.json
  package.json
  src/modules/_.loader.ts
  src/modules/providers/multer.provider.ts
  src/modules/providers/uuid.provider.ts
Labels: bug, feature, lib

#179 cupick@1.3.4.9
  .github/workflows/auto.deploy.yml
  package-lock.json
  package.json
  src/modules/_.loader.ts
  src/modules/providers/multer.provider.ts
  src/modules/providers/uuid.provider.ts
Labels: bug, feature, lib

#182 cupick@1.3.4.91
  package-lock.json
  package.json
  sql/default.sql
  sql/dev.sql
  sql/prod.sql
  sql/test.sql
  src/routes/services/profile.service.ts
  tsconfig.build.json
  tsconfig.json
Labels: bug

#184 cupick@1.3.4.92
  package.json
Labels: bug

#185 cupick@1.3.4.93
  .github/workflows/auto.deploy.yml
Labels: bug

#187 PR : 전체 레시피 조회 기능 수정 및 jest 튜닝
  .github/workflows/auto.deploy.yml
  jest.config.json
  jest/jest.config.e2e.json
  jest/jest.config.int.json
  jest/jest.config.unit.json
  package.json
  src/middlewares/middlewares/_.exporter.ts
  src/middlewares/middlewares/multer.middleware.ts
  src/middlewares/middlewares/token.middleware.ts
  src/models/_.loader.ts
  src/models/dtos/recipe/get.recipe.dto.ts
  src/models/dtos/recipe/recipe.dto.ts
  src/models/packets/i.recipe.like.packet.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/routers/comment.router.ts
  src/routes/routers/profile.router.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/recipe.service.ts
Labels: refactor

#188 cupick@1.3.5
  .github/workflows/auto.deploy.yml
  jest.config.json
  jest/jest.config.e2e.json
  jest/jest.config.int.json
  jest/jest.config.unit.json
  package.json
  src/middlewares/middlewares/_.exporter.ts
  src/middlewares/middlewares/multer.middleware.ts
  src/middlewares/middlewares/token.middleware.ts
  src/models/_.loader.ts
  src/models/dtos/recipe/get.recipe.dto.ts
  src/models/dtos/recipe/recipe.dto.ts
  src/models/packets/i.recipe.like.packet.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/routers/comment.router.ts
  src/routes/routers/profile.router.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/recipe.service.ts
Labels: refactor

#189 PR : 내 레시피, 좋아요 레시피 조회, #186
  src/models/packets/i.recipe.packet.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/profile.service.ts
Labels: refactor

#190 cupick@1.3.51
  src/models/packets/i.recipe.packet.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/profile.service.ts
Labels: refactor

#191 PR : Automated-Jest 의 node_modules cache, #166
  .github/workflows/auto.jest.runner.yml
Labels: refactor

#194 PR : `jest` tuning, #164
  jest.config.json
  jest/jest.config.e2e.json
  jest/jest.config.int.json
  jest/jest.config.unit.json
  package-lock.json
  package.json
  test/unit/routes/controllers/_.exporter.test.ts
Labels: lib, refactor, test

#200 PR : 일관성있는 mocking 을 위한 export defulat -> export 통일
  src/routes/controllers/_.exporter.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/profile.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/routers/_.exporter.ts
  src/routes/routers/auth.router.ts
  src/routes/routers/comment.router.ts
  src/routes/routers/profile.router.ts
  src/routes/routers/recipe.router.ts
Labels: refactor

#202 PR : 유지보수를 위한 DtoFactory 도입, #201
  src/models/_.loader.ts
  src/models/dtos/profile/get.like.recipe.dto.ts
  src/models/dtos/profile/get.my.recipe.dto.ts
  src/modules/_.loader.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/profile.controller.ts
  src/routes/controllers/recipe.controller.ts
Labels: refactor

#205 PR : HotFix SQL Table Query 의 insert 구문 오타 수정
  sql/default.sql
  sql/dev.sql
  sql/prod.sql
  sql/test.sql
Labels: bug

#206 PR : 회원가입에 선호 및 비선호 재료 선택 반영, #203
  sql/default.sql
  sql/dev.sql
  sql/prod.sql
  sql/test.sql
  src/models/dtos/request.query.extractor.ts
  src/models/dtos/user/signup.user.dto.ts
  src/models/dtos/user/user.dto.ts
  src/models/enums/_.exporter.ts
  src/models/enums/e.recipe.category.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/_.exporter.ts
  src/routes/repositories/user.category.repository.ts
  src/routes/services/auth.service.ts
Labels: refactor

#207 PR : 회원가입에 선호 및 비선호 재료 선택 반영
  src/models/dtos/profile/edit.profile.dto.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/profile.controller.ts
  src/routes/repositories/user.category.repository.ts
  src/routes/services/profile.service.ts
Labels: refactor

#216 cupick@1.3.6
  babel.config.json
  package-lock.json
  package.json
  sql/default.sql
  sql/dev.sql
  sql/erd/2022-09-19-ERD.mwb
  sql/erd/2022-09-23-ERD.mwb
  sql/prod.sql
  sql/test.sql
  src/models/_.loader.ts
  src/models/dtos/profile/edit.profile.dto.ts
  src/models/dtos/profile/get.like.recipe.dto.ts
  src/models/dtos/profile/get.my.recipe.dto.ts
  src/models/dtos/request.query.extractor.ts
  src/models/dtos/user/signup.user.dto.ts
  src/models/dtos/user/user.dto.ts
  src/models/enums/_.exporter.ts
  src/models/enums/e.recipe.category.ts
  src/modules/_.loader.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/_.exporter.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/profile.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/_.exporter.ts
  src/routes/repositories/user.category.repository.ts
  src/routes/routers/_.exporter.ts
  src/routes/routers/auth.router.ts
  src/routes/routers/comment.router.ts
  src/routes/routers/profile.router.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/auth.service.ts
  src/routes/services/profile.service.ts
  test/unit/routes/repositories/_.exporter.test.ts
Labels: feature

#220 cupick@1.3.63
  src/models/dtos/recipe/create.recipe.dto.ts
  src/models/dtos/recipe/update.recipe.dto.ts
Labels: bug

#221 PR : 내 프로필 조회 기능 구현
  src/models/_.loader.ts
  src/models/dtos/profile/get.my.profile.dto.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/profile.controller.ts
  src/routes/routers/profile.router.ts
  src/routes/services/profile.service.ts
Labels: feature

#222 HotFix 코멘트 전체 조회 응답 데이터 형식 변경
  src/constants/types/t.comment.response.ts
  src/routes/controllers/comment.controller.ts
  src/routes/repositories/comment.repository.ts
  src/routes/services/comment.service.ts
Labels: bug, feature

#223 PR : 레시피 상세 조회, ingredient_list 순서 뒤집히는 버그 수정
  src/routes/repositories/recipe.repository.ts
Labels: bug

#224 cupick@1.3.63
  src/constants/types/t.comment.response.ts
  src/models/_.loader.ts
  src/models/dtos/profile/get.my.profile.dto.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/profile.controller.ts
  src/routes/repositories/comment.repository.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/routers/profile.router.ts
  src/routes/services/comment.service.ts
  src/routes/services/profile.service.ts
Labels: bug, feature

#225 cupick@1.3.64
  src/routes/repositories/recipe.repository.ts
Labels: bug

#227 PR : 내가 좋아요한 레시피 버그 수정
  src/models/_.loader.ts
  src/models/packets/i.recipe.owner.packet.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/profile.service.ts
Labels: bug

#228 cupick@1.3.66
  src/models/_.loader.ts
  src/models/packets/i.recipe.owner.packet.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/profile.service.ts
Labels: bug

#230 cupick@1.3.68
  package-lock.json
  package.json
Labels: bug

#232 cupick@1.3.691
  appspec.yml
Labels: bug

#235 PR: Refactor 코드 컨벤션에 맞는 `리팩토링` 과 `Controller` 에서 직접 데이터 응답하는 로직 개선
  src/constants/_.loader.ts
  src/constants/types/t.comment.response.ts
  src/models/_.loader.ts
  src/models/packets/i.best.recipe.category.packet.ts
  src/models/packets/i.best.recipe.packet.ts
  src/modules/factory/dto.factory.ts
  src/modules/providers/dayjs.provider.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/ranking.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/comment.repository.ts
  src/routes/repositories/ranking.repository.ts
  src/routes/services/comment.service.ts
  src/routes/services/ranking.service.ts
Labels: refactor

#237 PR: Update 코멘트 업데이트 기능 응답 데이터 형식 수정
  src/routes/repositories/comment.repository.ts
  src/routes/services/comment.service.ts
Labels: feature

#243 PR: Hotfix/multer provider
  src/middlewares/middlewares/multer.middleware.ts
  src/modules/providers/multer.provider.ts
  src/modules/providers/uuid.provider.ts
Labels: bug, feature

#244 cupick@1.3.692
  .github/workflows/auto.jest.runner.yml
  jest.config.json
  jest/jest.config.e2e.json
  jest/jest.config.int.json
  jest/jest.config.unit.json
  package.json
  src/constants/_.loader.ts
  src/constants/error_list/error.list.ts
  src/constants/types/t.comment.response.ts
  src/middlewares/middlewares/multer.middleware.ts
  src/models/_.loader.ts
  src/models/packets/i.best.recipe.category.packet.ts
  src/models/packets/i.best.recipe.packet.ts
  src/modules/factory/dto.factory.ts
  src/modules/generator/random.generator.ts
  src/modules/providers/bcrypt.provider.ts
  src/modules/providers/dayjs.provider.ts
  src/modules/providers/multer.provider.ts
  src/modules/providers/mysql.provider.ts
  src/modules/providers/uuid.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/ranking.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/repositories/comment.repository.ts
  src/routes/repositories/ranking.repository.ts
  src/routes/services/auth.service.ts
  src/routes/services/comment.service.ts
  src/routes/services/ranking.service.ts
  src/server.ts
  test.txt
  test/_.fake.datas/fixture/_.exporter.ts
  test/_.fake.datas/fixture/models/dtos/user.dto.fixture.provider.ts
  test/_.fake.datas/fixture/models/enum/e.recipe.category.fixture.ts
  test/_.fake.datas/fixture/models/packets/packaet.fixture.provider.ts
  test/_.fake.datas/fixture/user.dto.fixture.provider.ts
  test/_.fake.datas/mocks/.gitkeep
  test/_.fake.datas/mocks/_.loader.ts
  test/_.fake.datas/mocks/http/node.mocks.https.ts
  test/_.fake.datas/mocks/modules/_.exporter.ts
  test/_.fake.datas/mocks/modules/factories/mock.dto.factory.ts
  test/_.fake.datas/mocks/modules/generators/mock.random.generator.ts
  test/_.fake.datas/mocks/modules/providers/mock.aws.ses.provider.ts
  test/_.fake.datas/mocks/modules/providers/mock.bcrypt.provider.ts
  test/_.fake.datas/mocks/modules/providers/mock.dayjs.provider.ts
  test/_.fake.datas/mocks/modules/providers/mock.jwt.provider.ts
  test/_.fake.datas/mocks/modules/providers/mock.mysql.provider.ts
  test/_.fake.datas/mocks/routes/_.exporter.ts
  test/_.fake.datas/mocks/routes/repositories/mock.auth.repository.ts
  test/_.fake.datas/mocks/routes/repositories/mock.auth.verify.list.repository.ts
  test/_.fake.datas/mocks/routes/repositories/mock.user.category.repository.ts
  test/_.fake.datas/mocks/routes/services/mock.auth.service.ts
  test/integration/sample.test.ts
  test/unit/constants/error_list/error.list.test.ts
  test/unit/modules/generator/random.generator.test.ts
  test/unit/modules/validators/joi.validator.test.ts
  test/unit/routes/controllers/_.exporter.test.ts
  test/unit/routes/controllers/auth.controller.test.ts
  test/unit/routes/services/auth.service.test.ts
Labels: bug, refactor
