Repository cupicks/cupicks-be, pull requests merged in 2022-10, with the labels that each got.

#247 PR : 배포 자동화 로직 개선 작업 (1차)
  .github/workflows/auto.deploy.yml
  .github/workflows/auto.jest.runner.yml
  appspec.yml
  content/nginx/cupick.ddns.net
  docs/ecosystem.config.json.sh.md
  ecosystem.config.json.sh
  package.json
  scripts/after-deploy.sh
  scripts/after-install.sh
  src/app.ts
  test.txt
Labels: bug

#248 PR: 1차 유저 피드백을 반영한 레시피 조회 로직 개선
  src/models/dtos/recipe/recipe.dto.ts
  src/models/packets/i.recipe.combined.packet.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/recipe.service.ts
Labels: bug, feature

#250 cupick@1.3.693 #248
  src/models/dtos/recipe/recipe.dto.ts
  src/models/packets/i.recipe.combined.packet.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/recipe.service.ts
Labels: feature

#252 PR: RefreshToken 인터페이스와 테스트 케이스 수정
  README.md
  src/modules/providers/jwt.provider.ts
  src/routes/services/auth.service.ts
  test/unit/routes/services/auth.service.test.ts
Labels: feature

#254 cupick@1.3.694
  src/modules/providers/jwt.provider.ts
  src/routes/services/auth.service.ts
  test/unit/routes/services/auth.service.test.ts
Labels: feature

#255 PR: 베스트 랭킹 레시피 조회에 댓글 갯수 응답 데이터 추가와 댓글 갯수 조회 쿼리에 올바른 Packet 타입 생성
  src/models/_.loader.ts
  src/models/packets/i.best.recipe.comment.packet.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/ranking.service.ts
  src/routes/services/recipe.service.ts
Labels: feature

#256 cupick@1.3.695
  src/models/_.loader.ts
  src/models/packets/i.best.recipe.comment.packet.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/ranking.service.ts
  src/routes/services/recipe.service.ts
Labels: feature

#257 PR: 레시피 상세 조회 쿼리와 응답 데이터 수정
  src/routes/repositories/recipe.repository.ts
  src/routes/services/recipe.service.ts
Labels: feature

#259 PR: 레시피 전체 조회 좋아요 갯수 응답 쿼리 수정과 올바른 Packet 생성
  src/models/packets/i.best.recipe.comment.packet.ts
  src/models/packets/i.recipe.like.packet.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/services/recipe.service.ts
Labels: bug

#263 PR: 주간 베스트 레시피 조회 전 주 레시피도 같이 조회되는 에러 수정
  src/models/dtos/comment/create.comment.dto.ts
  src/models/dtos/comment/update.comment.dto.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/comment.controller.ts
  src/routes/repositories/ranking.repository.ts
  src/routes/services/ranking.service.ts
Labels: bug

#264 cupick@1.3.698
  src/models/dtos/comment/create.comment.dto.ts
  src/models/dtos/comment/update.comment.dto.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/comment.controller.ts
  src/routes/repositories/ranking.repository.ts
  src/routes/services/ranking.service.ts
Labels: bug

#265 PR : 프로젝트 config 파일 정리 작업 및 README 업데이트
  ERD.png
  README.md
  package.json
  vite.config.ts
Labels: documentation

#267 PR : API 명세 수정에 의한 /auth 및 /profile 도메인 리팩토링
  src/models/dtos/profile/edit.profile.dto.ts
  src/models/dtos/user/confirm.email.dto.ts
  src/models/dtos/user/confirm.nickname.dto.ts
  src/models/dtos/user/reset.password.dto.ts
  src/models/dtos/user/send.email.dto.ts
  src/models/dtos/user/send.password.dto.ts
  src/models/dtos/user/signup.user.dto.ts
  src/modules/factory/dto.factory.ts
  src/modules/providers/dayjs.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/profile.controller.ts
  src/routes/routers/auth.router.ts
  test/_.fake.datas/fixture/models/dtos/user.dto.fixture.provider.ts
  test/_.fake.datas/fixture/user.dto.fixture.provider.ts
Labels: refactor

#242 PR : 공급자 클래스 단위 테스트 진행
  src/app.ts
  src/middlewares/filters/content-type/form.data.filter.ts
  src/middlewares/guards/cors/cors.guard.ts
  src/middlewares/guards/token/prevent.un.login.user.guard.ts
  src/models/env/private/env.private.ts
  src/modules/factory/dto.factory.ts
  src/modules/providers/bcrypt.provider.ts
  src/modules/providers/env.provider.ts
  src/modules/providers/jwt.provider.ts
  src/modules/providers/multer.provider.ts
  src/modules/providers/mysql.provider.ts
  tsconfig.build.json
  tsconfig.json
Labels: test

#269 cupick@1.4.01
  src/app.ts
  src/middlewares/filters/content-type/form.data.filter.ts
  src/middlewares/guards/cors/cors.guard.ts
  src/middlewares/guards/token/prevent.un.login.user.guard.ts
  src/models/env/private/env.private.ts
  src/modules/factory/dto.factory.ts
  src/modules/providers/bcrypt.provider.ts
  src/modules/providers/env.provider.ts
  src/modules/providers/jwt.provider.ts
  src/modules/providers/multer.provider.ts
  src/modules/providers/mysql.provider.ts
  tsconfig.build.json
  tsconfig.json
Labels: bug

#270 cupick@1.4.011
  src/routes/routers/auth.router.ts
Labels: bug

#271 cupick@1.4.011
  src/app.ts
  src/modules/providers/aws.ses.provider.ts
  src/modules/providers/bcrypt.provider.ts
  src/modules/providers/multer.provider.ts
  src/modules/providers/uuid.provider.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/comment.controller.ts
  src/routes/controllers/profile.controller.ts
  src/routes/controllers/ranking.controller.ts
  src/routes/controllers/recipe.controller.ts
  src/routes/repositories/auth.repository.ts
  src/routes/repositories/auth.verify.list.repository.ts
  src/routes/repositories/comment.repository.ts
  src/routes/repositories/ranking.repository.ts
  src/routes/repositories/recipe.ingredient.list.repository.ts
  src/routes/repositories/recipe.ingredient.repository.ts
  src/routes/repositories/recipe.repository.ts
  src/routes/repositories/user.category.repository.ts
  src/routes/routers/auth.router.ts
  src/routes/routers/comment.router.ts
  src/routes/routers/profile.router.ts
  src/routes/routers/recipe.router.ts
  src/routes/services/auth.service.ts
  src/server.ts
Labels: bug, refactor

#273 PR : 비밀번호 변경 도메인 수정, #272
  src/routes/controllers/auth.controller.ts
  src/routes/services/auth.service.ts
  test/unit/routes/controllers/auth.controller.test.ts
  test/unit/routes/services/auth.service.test.ts
Labels: refactor, test

#276 PR : 회원가입 도메인에 선호 및 비선호 체계 적용
  sql/README.md
  sql/migrations/2022-10-17-1210-create-recipe_cup_size.sql
  sql/migrations/2022-10-17-1217-update-recipe_category.sql
  sql/migrations/2022-10-18 1010-create-receip_temperature.sql
  sql/migrations/2022-10-18 1026-create-user_favor_cup_size.sql
  sql/migrations/2022-10-18 1028-create-user_disfavor_cup_size.sql
  sql/migrations/2022-10-18 1028-create-user_favor_cup_temperature.sql
  sql/migrations/2022-10-18 1030-create-user_disfavor_cup_temperature.sql
  sql/origins/default.sql
  sql/origins/dev.sql
  sql/origins/prod.sql
  sql/origins/test.sql
  src/models/_.loader.ts
  src/models/dtos/profile/edit.profile.dto.ts
  src/models/dtos/recipe/create.recipe.dto.ts
  src/models/dtos/recipe/update.recipe.dto.ts
  src/models/dtos/user/signup.user.dto.ts
  src/models/dtos/user/user.dto.ts
  src/models/enums/_.exporter.ts
  src/models/enums/e.recipe.category.ts
  src/models/enums/e.recipe.cup.size.ts
  src/models/enums/e.recipe.temperature.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/auth.controller.ts
  src/routes/repositories/user.category.repository.ts
  src/routes/repositories/user.favor.repository.ts
  src/routes/services/auth.service.ts
  test/unit/routes/repositories/user.favor.repository.test.ts
  test/unit/routes/services/auth.service.test.ts
Labels: feature, refactor, test

#277 PR : 프로필 수정 도메인에 선호 및 비선호 체계 적용
  src/models/dtos/profile/edit.profile.dto.ts
  src/models/dtos/user/signup.user.dto.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/profile.controller.ts
  src/routes/repositories/_.exporter.ts
  src/routes/repositories/user.favor.repository.ts
  src/routes/services/auth.service.ts
  src/routes/services/profile.service.ts
  test/unit/routes/repositories/_.exporter.test.ts
Labels: refactor, test

#278 cupick@1.4.1
  README.md
  package.json
  sql/README.md
  sql/migrations/2022-10-17-1210-create-recipe_cup_size.sql
  sql/migrations/2022-10-17-1217-update-recipe_category.sql
  sql/migrations/2022-10-18 1010-create-recipe_temperature.sql
  sql/migrations/2022-10-18 1026-create-user_favor_cup_size_list.sql
  sql/migrations/2022-10-18 1028-create-user_disfavor_cup_size_list.sql
  sql/migrations/2022-10-18 1028-create-user_favor_cup_temperature_list.sql
  sql/migrations/2022-10-18 1030-create-user_disfavor_cup_temperature_list.sql
  sql/origins/default.sql
  sql/origins/dev.sql
  sql/origins/prod.sql
  sql/origins/test.sql
  src/models/_.loader.ts
  src/models/dtos/profile/edit.profile.dto.ts
  src/models/dtos/recipe/create.recipe.dto.ts
  src/models/dtos/recipe/update.recipe.dto.ts
  src/models/dtos/user/signup.user.dto.ts
  src/models/dtos/user/user.dto.ts
  src/models/enums/_.exporter.ts
  src/models/enums/e.recipe.category.ts
  src/models/enums/e.recipe.cup.size.ts
  src/models/enums/e.recipe.temperature.ts
  src/modules/factory/dto.factory.ts
  src/routes/controllers/auth.controller.ts
  src/routes/controllers/profile.controller.ts
  src/routes/repositories/_.exporter.ts
  src/routes/repositories/user.category.repository.ts
  src/routes/repositories/user.favor.repository.ts
  src/routes/services/auth.service.ts
  src/routes/services/profile.service.ts
  test/jest.config.e2e.json
  test/jest.config.int.json
  test/jest.config.unit.json
  test/unit/routes/repositories/_.exporter.test.ts
  test/unit/routes/repositories/user.favor.repository.test.ts
  test/unit/routes/services/auth.service.test.ts
Labels: refactor
